import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    container: {
        backgroundColor: '#FFF',
    },
    btn: {
        width: 353,
        height: 56,
        paddingVertical: 17,
        paddingHorizontal: 112,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 100,
        backgroundColor: '#233972',
        gap: 10,
        marginBottom:16,
        marginHorizontal: 20,
    },
    signbtn: {
        width: 353,
        height: 56,
        backgroundColor: '#F9F9FC',
        paddingVertical: 17,
        paddingHorizontal: 112,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 100,
        gap: 10,
        marginHorizontal: 20,
    },
    txt: {
        width: 'auto',
        height: 'auto',
        color: '#FFF',
        fontSize: 16,
        fontWeight: "500",
        lineHeight: 20,
        fontStyle:'normal',
    },
    txtofSign: {
        width: 'auto',
        height: 'auto',
        color: '#110F24',
        fontSize: 16,
        fontWeight: "500",
        lineHeight: 20,
        fontStyle:'normal',
    },
    imghand:{
        width: 247.551,
      height: 214.662,
     marginHorizontal:73,
     marginBottom:123.34,

    },
    toptxt:{
        marginTop:0,
        left:70,
        right:70,
        width:263,
        height:68,
        color:'#00235B',
        textAlign:'center',
        fontSize:24,
        fontWeight:"600",
        lineHeight:34,
        letterSpacing:0.24,
        fontStyle:'normal',
    },
    imgsail:{
     width:90,
     height:100,
     marginTop:12,
     marginHorizontal:151,
     marginBottom:16,
    },
    lowertxt:{
        color:'rgba(17, 15, 36, 0.50)',
        textAlign:'center',
        fontSize:12,
        fontWeight:'400',
        lineHeight:24,
        letterSpacing:0.12,
        fontStyle:'normal',
    },
    toptxtcontainer:{
        marginBottom:42,
    }
});
export default styles;