const Data=[{image:require('../images/profile2user.png'),
                 name:"Zia Sharma",
                location:"Sector 11, Noida" },
                {image:require('../images/profile2user.png'),
                 name:"Zia Sharma",
                location:"Sector 11, Noida" },
                {image:require('../images/profile2user.png'),
                 name:"Zia Sharma",
                location:"Sector 11, Noida" },
                {image:require('../images/profile2user.png'),
                 name:"Zia Sharma",
                location:"Sector 11, Noida" },
                {image:require('../images/profile2user.png'),
                 name:"Zia Sharma",
                location:"Sector 11, Noida" },
                {image:require('../images/profile2user.png'),
                 name:"Zia Sharma",
                location:"Sector 11, Noida" },
                {image:require('../images/profile2user.png'),
                 name:"Zia Sharma",
                location:"Sector 11, Noida" },
                {image:require('../images/profile2user.png'),
                 name:"Zia Sharma",
                location:"Sector 11, Noida" },
                {image:require('../images/profile2user.png'),
                 name:"Zia Sharma",
                location:"Sector 11, Noida" },
                {image:require('../images/profile2user.png'),
                name:"Zia Sharma",
               location:"Sector 11, Noida" }, {image:require('../images/profile2user.png'),
               name:"Zia Sharma",
              location:"Sector 11, Noida" }, {image:require('../images/profile2user.png'),
              name:"Zia Sharma",
             location:"Sector 11, Noida" }, {image:require('../images/profile2user.png'),
             name:"Zia Sharma",
            location:"Sector 11, Noida" },
                
                ]
                export default Data;